
include:
  - board: akdk_bt1
    shield: trackpad_glp3_w
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artificial-name: trackpad-glp3-w
  - board: akdk_bt1
    shield: settings_reset
    artificial-name: settings_reset-akdk_bt1-zmk
